---
# This playbook contains common plays that will be run on all nodes.

- name: Configure sources.list
  copy: src=apt/sources.list dest=/etc/apt/sources.list

- name: Add an apt key
  apt_key: keyserver=keyserver.ubuntu.com id=16126D3A3E5C1192

- name: Install software-properties-common
  apt: name=software-properties-common state=present
  
- name: Add gangbang linux repository
  apt_repository: repo='ppa:arnaud-morin/gangbang-linux'
  
- name: Add webupd8team repository
  apt_repository: repo='ppa:webupd8team/java'
  
- name: Accept java license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install packages
  apt: update_cache=yes name={{ item }} state=present
  with_items: "{{ packages }}"

- name: Copy binaries
  copy: src=bin/ dest=/usr/local/bin/ mode=a+x

- name: Copy config and themes to home dir
  synchronize: src={{ item }}/ dest=/home/{{ ansible_env.SUDO_USER }}/.{{ item }}/
  with_items:
    - themes
    - config

- name: Set permissions user and group to home dir
  file: name=/home/{{ ansible_env.SUDO_USER }}/.{{ item }} owner={{ ansible_env.SUDO_USER }} group={{ ansible_env.SUDO_USER }} recurse=yes
  with_items:
    - themes
    - config
    - 

- name: Copy xscreensaver config file
  copy: src=xscreensaver dest=/home/{{ ansible_env.SUDO_USER }}/.xscreensaver

- name: Create default home dirs
  file: name=/home/{{ ansible_env.SUDO_USER }}/{{ item }} owner={{ ansible_env.SUDO_USER }} group={{ ansible_env.SUDO_USER }} state=directory
  with_items:
    - downloads
    - documents
    - videos
    - images

