---
# This playbook install gangbang linux on a fresh ubuntu vivid install

- name: install gangbang linux on a fresh ubuntu vivid install
  hosts: all
  remote_user: ubuntu
  become: yes

  roles:
    - gangbang
